module.exports = {
  apps: [
    {
      name: 'price-tracker-bot',
      script: 'src/index.js',
      cwd: __dirname,
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: 10000,
      env: {
        NODE_ENV: 'production',
      },
      env_file: '.env',
      log_file: 'logs/pm2/bot.log',
      error_file: 'logs/pm2/bot-error.log',
      out_file: 'logs/pm2/bot-out.log',
      pid_file: 'logs/pm2/bot.pid',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      kill_timeout: 10000,
      listen_timeout: 8000,
      shutdown_with_message: true,
    },
    {
      name: 'price-tracker-api',
      script: 'api/server.js',
      cwd: __dirname,
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '300M',
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: 10000,
      env: {
        NODE_ENV: 'production',
      },
      env_file: '.env',
      log_file: 'logs/pm2/api.log',
      error_file: 'logs/pm2/api-error.log',
      out_file: 'logs/pm2/api-out.log',
      pid_file: 'logs/pm2/api.pid',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      kill_timeout: 10000,
      listen_timeout: 8000,
    },
  ],
};
